<!DOCTYPE html>
<html lang="uk">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Віртуальна галерея "Золотого віку" іспанського живопису</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <header>
        <h1>Віртуальна галерея "Золотого віку" іспанського живопису</h1>
        <p>Перегляньте найкращі роботи видатних митців XVI-XVII століття.</p>
        <nav>
            <ul>
                <li><a href="#velazquez">Дієго Веласкес</a></li>
                <li><a href="#zurbaran">Франсиско де Сурбаран</a></li>
                <li><a href="#murillo">Бартоломе Естебан Мурільйо</a></li>
                <li><a href="#ribera">Хосе де Рібера</a></li>
                <li><a href="#greco">Ель Греко</a></li>
            </ul>
        </nav>
    </header>
    <main>
        <section id="velazquez">
            <h2>Дієго Веласкес</h2>
            <p>Один із найвпливовіших митців. Його роботи вирізняються реалістичним підходом.</p>
            <ul>
                <li>"Меніни"</li>
                <li>"Триумф Вакха"</li>
                <li>"Портрет папи Інокентія X"</li>
            </ul>
            <img src="velazquez.jpg" alt="Дієго Веласкес">
        </section>
        <section id="zurbaran">
            <h2>Франсиско де Сурбаран</h2>
            <p>Майстер релігійного живопису. Відомий увагою до деталей та драматичним освітленням.</p>
            <ul>
                <li>"Святий Серпій"</li>
                <li>"Натюрморт з лимонами"</li>
                <li>"Свята Касильда"</li>
            </ul>
            <img src="zurbaran.jpg" alt="Франсиско де Сурбаран">
        </section>
        <section id="murillo">
            <h2>Бартоломе Естебан Мурільйо</h2>
            <p>Його картини наповнені емоціями і теплом, часто присвячені релігійним сюжетам.</p>
            <ul>
                <li>"Непорочне зачаття"</li>
                <li>"Хлопчики, які їдять фрукти"</li>
                <li>"Свята Родина з птахом"</li>
            </ul>
            <img src="murillo.jpg" alt="Бартоломе Естебан Мурільйо">
        </section>
        <section id="ribera">
            <h2>Хосе де Рібера</h2>
            <p>Майстер драматичного реалізму, що поєднує іспанські й італійські традиції.</p>
            <ul>
                <li>"Мучеництво Святого Бартоломея"</li>
                <li>"Святий Андрій"</li>
                <li>"Філософи"</li>
            </ul>
            <img src="ribera.jpg" alt="Хосе де Рібера">
        </section>
        <section id="greco">
            <h2>Ель Греко</h2>
            <p>Унікальний стиль, який поєднує візантійські традиції та ренесансний гуманізм.</p>
            <ul>
                <li>"Поховання графа Оргаса"</li>
                <li>"Погляд на Толедо"</li>
                <li>"Святий Мартін і жебрак"</li>
            </ul>
            <img src="greco.jpg" alt="Ель Греко">
        </section>
    </main>
    <footer>
        <p>© 2024 Віртуальна галерея іспанського живопису</p>
        <p>Контакти: info@spanishartgallery.com</p>
    </footer>
</body>
</html>

body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 0;
    background-color: #f4f4f9;
    color: #333;
}

header {
    background-color: #2c3e50;
    color: #fff;
    padding: 20px;
    text-align: center;
}

nav ul {
    list-style: none;
    padding: 0;
}

nav ul li {
    display: inline;
    margin: 0 15px;
}

nav ul li a {
    color: #fff;
    text-decoration: none;
}

main {
    padding: 20px;
}

section {
    margin-bottom: 40px;
}

section img {
    max-width: 100%;
    height: auto;
    display: block;
    margin: 10px auto;
}

footer {
    background-color: #2c3e50;
    color: #fff;
    text-align: center;
    padding: 10px 0;
    position: fixed;
    bottom: 0;
    width: 100%;
}
